//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3UsersLogin
    {
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Email { get; set; }
        public string PictureURL { get; set; }
        public string Roles { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<byte> IsApply { get; set; }
        public string KeyStringValidEmail { get; set; }
        public string Url { get; set; }
    }
}
